#ifndef MP_ASSETS_H
#define MP_ASSETS_H

#include <stddef.h>

typedef enum {
    ASSET_BACK_BLACK_SVG,
    ASSET_FORWARD_BLACK_SVG,
    ASSET_PAUSE_BLACK_SVG,
    ASSET_PLAY_BLACK_SVG,
    ASSET_REPEAT_BLACK_SVG,
    ASSET_REPEAT_ONE_BLACK_SVG,
    ASSET_SETTINGS_BLACK_SVG,
    ASSET_SHUFFLE_BLACK_SVG,
    ASSET_PLAYLIST_DARK_SVG,
    ASSET_BACK_WHITE_SVG,
    ASSET_FORWARD_WHITE_SVG,
    ASSET_PAUSE_WHITE_SVG,
    ASSET_PLAY_WHITE_SVG,
    ASSET_REPEAT_WHITE_SVG,
    ASSET_REPEAT_ONE_WHITE_SVG,
    ASSET_SETTINGS_WHITE_SVG,
    ASSET_SHUFFLE_WHITE_SVG,
    ASSET_PLAYLIST_LIGHT_SVG,
    ASSET_ICON_PNG,
    ASSET_OPEN_SANS_REGULAR_TTF,
    ASSET_COUNT,
} Asset_Id;

typedef struct {
    const unsigned char *data;
    size_t size;
    const char *name;
} Embedded_Asset;

Embedded_Asset asset_get(Asset_Id id);

#endif
